### ISSUE TITLE
Unable to edit resource with Action Button

### ISSUE THREAD

**Issue by HeadStudios** [pavloniym/nova-action-buttons#2]
I am unable to edit a resource as long as the ActionButton field is inside - once I remove it - it works fine. It's working perfectly in Index but being unable to edit resources when it is setup makes it impossible for me to use. Any hacks/fixes or any further questions happy to answer.

Video for context:
https://share.getcloudapp.com/GGu78DL7

**Comment by HeadStudios** [comment]
Please disregard, I have found solution by adding hideWhenUpdating() to Buttons which has solved my error.

**Comment by pavloniym** [comment]
Thank you!
Fixed this in new release (v1.0.1) — now field is hidden on update/detail/creation views, so nova should update resources correctly

https://github.com/pavloniym/nova-action-buttons/releases/tag/v1.0.1
