### ISSUE TITLE
Enable title on button

### ISSUE THREAD

**Issue by LorenzoSapora** [pavloniym/nova-action-buttons#5]
This feature is already partially complete in the current version. Line 3 of `ActionButtonField.vue` `:title="name"` is called, but computed as `const name = computed(() => props?.field?.name || null);`, and name isn't called in ActionButton::class. All it would require is adding

```php
    public function title(string $title): self
    {
        return $this->withMeta(compact('title'));
    }
```

And hooking it up.

**Comment by pavloniym** [comment]
Hello
There is no need in additional title method!
You can add `name` in constructor of action:

```php
ActionButtons::make('Torrent actions')
```
```php
ActionButton::make('Upload')
```

![image](https://user-images.githubusercontent.com/17234942/227599946-8264830f-9887-4a27-9b2e-8282b3a07747.png)

I hope this will help you!

**Comment by LorenzoSapora** [comment]
Ah! How could I have been so blind! Thank you, I went too deep thinking it was a partial feature, when I should have just added a string to the title :)
